### ISSUE TITLE
项目跑通一些心得

### ISSUE THREAD

**Issue by zzlxhczy** [lyric777/Book-Management-System#12]
1.版本问题，主要应该是下面几个
Flask==1.1.4
Flask-Login==0.6.2
Flask-Script==2.0.6
Flask-SQLAlchemy==2.5.1
Flask-WTF==1.1.1
SQLAlchemy==1.4.0
2.用户名密码已经被修改了，建议用navicat连上SQLite查看，方便查看其他数据。SQLite环境也要装好
管理员：201801     123

其他应该就没啥了，还有问题可以加V 13736625256

**Comment by zzlxhczy** [comment]
在帮网友解答过程中，如果需要用到首页的echarts折线图展示，需要将 index.html 的echarts的在线js地址做变更

**Comment by chunfanhuen** [comment]
我附议，上面兄弟说的，我就是根据他说的点，修改了一下就跑通了

**Comment by adady** [comment]
markupsafe==2.0.1

**Comment by LiangJie803** [comment]
D:\Python\python.exe D:\Book-Management-System-master\Book-Management-System-master\book_management_sys.py 
D:\Python\Lib\site-packages\flask_sqlalchemy\__init__.py:872: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  warnings.warn(FSADeprecationWarning(
Traceback (most recent call last):
  File "D:\Book-Management-System-master\Book-Management-System-master\book_management_sys.py", line 497, in <module>
    manager.run()
    ~~~~~~~~~~~^^
  File "D:\Python\Lib\site-packages\flask_script\__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "D:\Python\Lib\site-packages\flask_script\__init__.py", line 359, in handle
    kwargs = app_namespace.__dict__
             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__dict__'. Did you mean: '__dir__'?
这是什么错误:(
